export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  { title: "Fuel", value: "" },
  { title: "Gas", value: "Gas" },
  { title: "Electricity", value: "Electricity" },
];

export const cars: {
  id: number;
  manufacturer: string;
  model: string;
  year: string;
  fuel: string;
  engine: string;
  image: string;
  pricePerDay: number;
  transmission: string;
  drive: string;
  kmPerLitre: number;
}[] = [
  {
    id: 1,
    manufacturer: "BMW",
    model: "M3 E46",
    year: "2003",
    fuel: "Gas",
    engine: "3.2L I6",
    image: "/m3.png",
    pricePerDay: 120,
    transmission: "Manual",
    drive: "RWD",
    kmPerLitre: 8,
  },
  {
    id: 2,
    manufacturer: "Tesla",
    model: "Model S",
    year: "2021",
    fuel: "Electricity",
    engine: "Dual Motor Electric",
    image: "/tesla-model-s.png",
    pricePerDay: 250,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 0,
  },
  {
    id: 3,
    manufacturer: "Audi",
    model: "A4",
    year: "2019",
    fuel: "Gas",
    engine: "2.0L I4 Turbo",
    image: "/audi-a4.png",
    pricePerDay: 100,
    transmission: "Automatic",
    drive: "FWD",
    kmPerLitre: 12,
  },
  {
    id: 4,
    manufacturer: "Toyota",
    model: "Corolla",
    year: "2020",
    fuel: "Gas",
    engine: "1.8L I4",
    image: "/toyota-corolla.png",
    pricePerDay: 80,
    transmission: "Automatic",
    drive: "FWD",
    kmPerLitre: 15,
  },
  {
    id: 5,
    manufacturer: "Honda",
    model: "Civic",
    year: "2018",
    fuel: "Gas",
    engine: "2.0L I4",
    image: "/honda-civic.png",
    pricePerDay: 85,
    transmission: "Automatic",
    drive: "FWD",
    kmPerLitre: 14,
  },
  {
    id: 6,
    manufacturer: "Hyundai",
    model: "Elantra",
    year: "2021",
    fuel: "Gas",
    engine: "2.0L I4",
    image: "/hyundai-elantra.png",
    pricePerDay: 75,
    transmission: "Automatic",
    drive: "FWD",
    kmPerLitre: 16,
  },
  {
    id: 7,
    manufacturer: "Lexus",
    model: "RX 350",
    year: "2019",
    fuel: "Gas",
    engine: "3.5L V6",
    image: "/lexus-rx350.png",
    pricePerDay: 120,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 10,
  },
  {
    id: 8,
    manufacturer: "Subaru",
    model: "Outback",
    year: "2020",
    fuel: "Gas",
    engine: "2.5L H4",
    image: "/subaru-outback.png",
    pricePerDay: 95,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 12,
  },
  {
    id: 9,
    manufacturer: "Toyota",
    model: "Camry",
    year: "2022",
    fuel: "Gas",
    engine: "2.5L I4",
    image: "/toyota-camry.png",
    pricePerDay: 90,
    transmission: "Automatic",
    drive: "FWD",
    kmPerLitre: 14,
  },
  {
    id: 10,
    manufacturer: "Honda",
    model: "Accord",
    year: "2021",
    fuel: "Gas",
    engine: "1.5L I4 Turbo",
    image: "/honda-accord.png",
    pricePerDay: 95,
    transmission: "Automatic",
    drive: "FWD",
    kmPerLitre: 14,
  },
  {
    id: 11,
    manufacturer: "Hyundai",
    model: "Tucson",
    year: "2020",
    fuel: "Gas",
    engine: "2.0L I4",
    image: "/hyundai-tucson.png",
    pricePerDay: 85,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 12,
  },
  {
    id: 12,
    manufacturer: "Lexus",
    model: "ES 250",
    year: "2018",
    fuel: "Gas",
    engine: "2.5L I4",
    image: "/lexus-es250.png",
    pricePerDay: 110,
    transmission: "Automatic",
    drive: "FWD",
    kmPerLitre: 11,
  },
  {
    id: 13,
    manufacturer: "Subaru",
    model: "Forester",
    year: "2021",
    fuel: "Gas",
    engine: "2.5L H4",
    image: "/subaru-forester.png",
    pricePerDay: 90,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 12,
  },
  {
    id: 14,
    manufacturer: "Mercedes-Benz",
    model: "C-Class",
    year: "2019",
    fuel: "Gas",
    engine: "2.0L I4 Turbo",
    image: "/mercedes-c-class.png",
    pricePerDay: 130,
    transmission: "Automatic",
    drive: "RWD",
    kmPerLitre: 9,
  },
  {
    id: 15,
    manufacturer: "Mercedes-Benz",
    model: "E-Class",
    year: "2020",
    fuel: "Gas",
    engine: "3.0L I6",
    image: "/mercedes-e-class.png",
    pricePerDay: 150,
    transmission: "Automatic",
    drive: "RWD",
    kmPerLitre: 10,
  },
  {
    id: 16,
    manufacturer: "Audi",
    model: "Q5",
    year: "2021",
    fuel: "Gas",
    engine: "2.0L I4 Turbo",
    image: "/audi-q5.png",
    pricePerDay: 140,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 11,
  },
  {
    id: 17,
    manufacturer: "Audi",
    model: "A6",
    year: "2018",
    fuel: "Gas",
    engine: "2.0L I4 Turbo",
    image: "/audi-a6.png",
    pricePerDay: 145,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 10,
  },
  {
    id: 18,
    manufacturer: "BMW",
    model: "X3",
    year: "2020",
    fuel: "Gas",
    engine: "2.0L I4 Turbo",
    image: "/bmw-x3.png",
    pricePerDay: 135,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 11,
  },
  {
    id: 19,
    manufacturer: "Tesla",
    model: "Model 3",
    year: "2022",
    fuel: "Electricity",
    engine: "Dual Motor Electric",
    image: "/tesla-model-3.png",
    pricePerDay: 200,
    transmission: "Automatic",
    drive: "RWD",
    kmPerLitre: 0,
  },
  {
    id: 20,
    manufacturer: "Toyota",
    model: "RAV4",
    year: "2021",
    fuel: "Gas",
    engine: "2.5L I4",
    image: "/toyota-rav4.png",
    pricePerDay: 100,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 13,
  },
  {
    id: 21,
    manufacturer: "Hyundai",
    model: "Santa Fe",
    year: "2022",
    fuel: "Gas",
    engine: "2.5L I4",
    image: "/hyundai-santa-fe.png",
    pricePerDay: 105,
    transmission: "Automatic",
    drive: "AWD",
    kmPerLitre: 12,
  },
];